### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by algattsm** [candlecorp/wick#123]
**Is your feature request related to a problem? Please describe.**

The documentation could be improved for better understand of the various features.

**Propose a solution**

It's nice to have some basic input and output regarding the actions for example, it would be beneficial to have some additional details regarding the intent of each action and possibly some examples of using them.

**Describe alternatives you've considered**

I resorted to looking at some of the golang tests included in your code to understand the actions better. 

**Additional context**

**Comment by fawadasaurus** [comment]
Hi @algattsm 

Would it be sufficient to link each page to an implementation in the examples repo? Or maybe a BDD test?

We should be able to add some description for each of the actions.

**Comment by algattsm** [comment]
Yes! I think this would be a great start for sure. This would save the trouble of going back and forth between examples to try and find where the action is used.

The description of each action would also be super helpful in understanding the intent of some of them.

**Comment by jsoverson** [comment]
Docs have started improving at https://candle.dev/docs and the rustdoc is now generated here: https://candle.dev/docs/rustdoc

Closing this issue as documentation has improved and will be an ongoing process.
