### ISSUE TITLE
Being able to push more than 1 file, maybe a directory to the registry 

### ISSUE THREAD

**Issue by shazaibn** [candlecorp/wick#150]
**Is your feature request related to a problem? Please describe.**
The `wick registry push` command works as intended but i can only push one file at a time. 
If I have an application with multiple files, I'd like to be able to upload everything in one push.

**Propose a solution**
Add functionality to the push command for us to be able to push multiple files or a directory to the registry. 

**Describe alternatives you've considered**
I tried to upload 2 files individually but then I get a seperate URL for both files and I don't believe that is how we intend for our registry to be used.

**Comment by jsoverson** [comment]
Added in #178
