### ISSUE TITLE
HTTP Request Client Resource

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#177]
**Is your feature request related to a problem? Please describe.**
We need a way to make HTTP requests to external resources (ex: rest api).

**Propose a solution**
Create a HTTP request resource (similar to rust library reqwest)
Needs to handle HTTPS/TLS.
Needs to be tightly controlled.  The setup must define a set of hostname matchers. The hostname matchers must be exact matches at the root domain level, wildcards may be supported at the subdomain level:
ex:
```yaml
...
allowed_hostnames: //this is required
  - candle.dev
  - *.candle.dev
  - google.com
  - *.com //this is NOT allowed
```

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by jsoverson** [comment]
Implemented in #217
