### ISSUE TITLE
Assets not listing icon

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#183]
**Describe the bug**
When I get the asset list from parsing a component config, it does not list the icon as an asset.

**To Reproduce**
Create a component with icon metadata.  It does not show up in the asset list.

**Expected behavior**
All included files (such as icons) should show up in the asset list.

**Actual behavior**
The icon does not show up.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Fixed via #178
