### ISSUE TITLE
Reserved Keywords not allowed for component operation names

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#206]
**Describe the bug**
I am creating a component with an operation named `match`
![image](https://user-images.githubusercontent.com/99134191/233365587-410f523c-aeff-42f5-90d0-ee8109390463.png)

**To Reproduce**
Create a component with an operation named `match`

**Expected behavior**
I expect to be able to create any string operation name and not have reserved keywords.

**Actual behavior**
The component does not compile.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Fixed via #226
