### ISSUE TITLE
Passing int below 128 as part of `Value` to Component sends Nil

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#213]
**Describe the bug**
Trying to pass integer as a `Value` is not encoding properly to integer.

**To Reproduce**
https://github.com/candlecorp/wick-components/tree/main/components/string_template

clone the project, run just debug and run this command:
```
wick invoke component.yaml render -- --template "Hello, {{name}}! Your age is {{age}}" --parameters '{"name": "John", "age": 30}'

params: {"name": String("John"), "age": Null}
globals: {"name": Scalar(Str("John")), "age": Nil}
{"payload":{"value":"Hello, John! Your age is "},"port":"output"}
```

**Expected behavior**
It should work with all numbers

**Actual behavior**
It only works with numbers above 127:
```
wick invoke component.yaml render -- --template "Hello, {{name}}! Your age is {{age}}" --parameters '{"name": "John", "age": 128}'

params: {"age": Number(128), "name": String("John")}
globals: {"name": Scalar(Str("John")), "age": Scalar(Integer(128))}
{"payload":{"value":"Hello, John! Your age is 128"},"port":"output"}
```

**Environment:**
 - OS: OSX
 - Architecture: AARCH64
 - Build Version: 0.6.0

**Additional context**
None

**Comment by jsoverson** [comment]
Fixed with #217 with an updated codec library.
