### ISSUE TITLE
Wick Native "Entropy" Component

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#215]
**Is your feature request related to a problem? Please describe.**
In order to do crypto and random functions in WebAssembly, they need some type of entropy.

**Propose a solution**
There should be a native component that generates entropy.  This would allow a wick component to do some cryptography and generating random numbers, etc.

**Describe alternatives you've considered**
Wick could automatically pass an entropy value (along with start execution time) to all components.

**Additional context**
None

**Comment by jsoverson** [comment]
Fixed via #226
