### ISSUE TITLE
Package Static Files

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#218]
**Is your feature request related to a problem? Please describe.**
When I want to serve a website, I want to package my website HTML/images/etc with my wick app so that it is all included in a single package.

**Propose a solution**
Create a `package` section with `files` to specify additional files that need to be included in the package.
```
package:
  files:
    - ./html/ #entire directory
    - ./assets/file.png #single file
```

This can all be tar'd up into a single layer in the package.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jsoverson** [comment]
Implemented in #219
