### ISSUE TITLE
Access Logs for HTTP Trigger

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#223]
**Is your feature request related to a problem? Please describe.**
Feature request. There should be access logs for every request for the HTTP trigger component.

**Propose a solution**
Really, there should be logs for all components but for any server type component ( like HTTP), it is now expected that they emit logs to stdout/stderr so that they can be collected by the container runtime. Additionally, for HTTP servers it is expected to see logs so it is easy to see the traffic coming into the application.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jsoverson** [comment]
Addressed in #237
