### ISSUE TITLE
ctx argument missing in rust template lib.rs

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#234]
**Describe the bug**
When you generate a new project, it should have an accurate example for the lib.rs with context

**To Reproduce**
`cargo generate candlecorp/wick templates/rust --name foo`

**Expected behavior**
the lib.rs should have the context argument

**Actual behavior**
the lib.rs does not have the context argument

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
fixed in #243
