### ISSUE TITLE
Breaking due to outputs

### ISSUE THREAD

**Issue by shazaibn** [candlecorp/wick#239]
**Describe the bug**
The SQL component is breaking even when we give the outputs that it is asking for

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
A clear and short description of what you expected to happen.

**Actual behavior**
A clear and short description of what actually happens.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Closed via #240
