### ISSUE TITLE
postgres sql component doesn't understand unsigned ints

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#245]
**Describe the bug**
the sql data conversion doesn't understand unsigned ints

**To Reproduce**
Create an input of type u32 for a sql query operation and you will get the error:
ecuting query error=Failed to fetch result of query: Failed to fetch result of query: error returned from database: incorrect binary data format in bind parameter 2

**Expected behavior**
the data works properly as a u32

**Actual behavior**
data does not work as it can not be converted to proper format for postgres

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
fixed #273
