### ISSUE TITLE
sql component hangs on error when called using wasmrs component

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#246]
**Describe the bug**
if the query generates an error in the database, the wasmrs component hangs.  It does not return any response and will not accept any new requests.

**To Reproduce**
Create a wasmrs component and call a query that has an error in it.

**Expected behavior**
The error is propagated up and error http status code is sent to client

**Actual behavior**
application hangs

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Fixed via #278
