### ISSUE TITLE
timestamp or date not working with wasmrs and sql component

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#247]
**Describe the bug**
I was unable to determine how to pass a timestamp that was originally a string to a sql database where it was expecting a timestamp. Attempted to use the `datetime` type but was not successful.

**To Reproduce**
Create a postgres table with timestamp type column and make a wasmrs call with a string.

**Expected behavior**
There should be a documented way to do this.

**Actual behavior**
Unable to do this.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Fixed via #273
