### ISSUE TITLE
Create SQL integration test component

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#248]
**Is your feature request related to a problem? Please describe.**
Need a component that shows all the sql and wick types and how they relate.

**Propose a solution**
create component with test db table.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jsoverson** [comment]
Started in #273, keeping this open until all types are tested.

**Comment by jsoverson** [comment]
Closing as we now have basic coverage across sql server, postgres, and sqlite.
