### ISSUE TITLE
Installation Problem on Ubuntu:Jammy

### ISSUE THREAD

**Issue by algattsm** [candlecorp/wick#265]
**Describe the bug**
I'm trying to run the install `curl -sSL sh.wick.run | bash` on an ubuntu docker container and the install is failing.

**To Reproduce**

1. docker run -it -p 8888:8888 ubuntu:jammy /bin/bash
2. apt update && apt install ca-certificates curl
3. curl -sSL sh.wick.run | bash

**Expected behavior**
successful install

**Actual behavior**
root@67a61a64c30f:/# curl -sSL sh.wick.run | bash
mktemp: too few X's in template 'candlecorp-wick-install'
Installing wick latest
This will install wick to /root/.wick/bin.

Your system is detected to be linux-amd64
Downloading https://github.com/candlecorp/wick/releases/latest/download/wick-linux-amd64.tar.gz...
Downloaded archive to /wick-linux-amd64.tar.gz...
Removing any existing components...
tar: : Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Copying files to /root/.wick/bin
Failed to unpack /wick.

Failed to install wick.
You can try building a custom version from source at https://github.com/candlecorp/wick/
For support, go to https://candle.dev/, join our Discord https://discord.gg/candle or reach out to us on Twitter @candle_corp.
root@67a61a64c30f:/# 

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Thanks @algattsm, this has been fixed on the `main` branch via https://github.com/candlecorp/wick/pull/266
