### ISSUE TITLE
Send "with" configs using wasmrs rust host call

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#280]
**Is your feature request related to a problem? Please describe.**
I need to call a host function that has `with` and arguments.  I am able to send the arguments using rust code but I do not have a way to pass the `with` arguments.

**Propose a solution**
Need ability to send `with` values when invoking host call:

```rust

let insert_card_payload = packet_stream!(("card_number", card_number), ("card_type", card_type));
let with_vals: Value = json!({
                "foo": "a",
                "bar": "b"
            });
let mut insert_card_response = provided.db.insert_card(insert_card_payload, with_vals)?;

```

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by jsoverson** [comment]
This was added via #289. An example of how to pass configuration to a provided component can be found here: https://github.com/candlecorp/wick/blob/main/crates/integration/test-cli-trigger-component/src/lib.rs#L35
