### ISSUE TITLE
Breaking when invoking any query operation

### ISSUE THREAD

**Issue by shazaibn** [candlecorp/wick#288]
**Describe the bug**
When invoking a component that queries a DB, we get an error saying missing query parameters

**To Reproduce**
Invoke an operation in a component that takes in inputs and queries a DB

**Expected behavior**
Expected to return any result matching query

**Actual behavior**
Instead, we get this: 

`2023-05-31T20:09:53 ERROR request: internal error time=31/May/2023:16:09:53 -0400 path="/api/sales" error=Operation error: Missing query parameters: `

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Fixed via #287
