### ISSUE TITLE
SQL "on_error: Ignore" should not error the flow

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#342]
**Is your feature request related to a problem? Please describe.**
in a DB component, when I say `on_error: Ignore`, it should log the error but not throw an error to the calling operation. There are times that I will be inserting a lot of data and some duplicates will not be allowed by the database and that is ok. When all the inserts are done, I want to commit the records that were not duplicates.

**Propose a solution**
Keep going and not throw an error.

**Describe alternatives you've considered**
None

**Additional context**
none

**Comment by jsoverson** [comment]
Marking as wont-fix. `Ignore` will still propagate errors, it just won't kill a stream. Filtering out errors can be better done downstream.
