### ISSUE TITLE
SQL split `query` into `exec`

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#343]
**Is your feature request related to a problem? Please describe.**
There should be a different between queries that return a dataset and queries that make a change. Queries that make a change should return a bool or int.

**Propose a solution**
`query` should be used when we want to return a dataset
`exec` should be used when you don't want to return a `dataset`

**Describe alternatives you've considered**
None

**Additional context**

**Comment by jsoverson** [comment]
Deferring this until there's a new reason for it. The initial reason #332 turned out to be a non-issue.

**Comment by fawadasaurus** [comment]
addressed by #345
