### ISSUE TITLE
Support Union Type

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#350]
**Is your feature request related to a problem? Please describe.**
Right now we can only have a single type of input or output.  There are use cases (like middleware) where a output can be either HttpRequest or HttpResponse

**Propose a solution**
Support union types so that we can use multiple types in a single input without having to resort to "object". 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jsoverson** [comment]
Added via #355
