### ISSUE TITLE
Add "Import" awareness for Wasmrs components

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#369]
**Is your feature request related to a problem? Please describe.**
Currently a wasmrs component only supports "requires" to use other components.  This makes it required to have a composite component in front of a wasmrs component. 

**Propose a solution**
Allow Import to work with Wasmrs components so that it is no longer mandatory to use the `requires` interface for having wasm connect to other components.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jsoverson** [comment]
Added via #433
