### ISSUE TITLE
Tracing does not start from time trigger

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#402]
**Describe the bug**
The traces were not being set to the Otel collector for the time trigger actions.

**To Reproduce**
Set up time trigger and http trigger app.
configure OTLP_ENDPOINT env variable and the time trigger will not send any traces but http trigger will.

**Expected behavior**
Both should send traces. The root span for the time trigger should be each time that the trigger was executed.

**Actual behavior**
Only http trigger requests create a root span.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
Closing as fixed, feel free to reopen if it's not @fawadasaurus
