### ISSUE TITLE
Can't install wick with any of the commands

### ISSUE THREAD

**Issue by rnealson** [candlecorp/wick#442]
**Describe the bug**
I tried to install wick and the first command, `cargo install wick-cli`, didn't work because I didn't have Rust installed on this system. The second command, `brew install candlecorp/tap/wick`, didn't work because I don't have homebrew installed on my macbook air. The third command `curl -sSL sh.wick.run | bash` errored out with 

```
Installing wick latest
This will install wick to ~/.wick/bin.



Sorry, there is no prebuilt binary for operating system and architecture: 'darwin-amd64'.



Failed to install wick.
You can try building a custom version from source at https://github.com/candlecorp/wick/
For support, go to https://candle.dev/, join our Discord https://discord.gg/candle or reach out to us on Twitter @candle_corp.
```

**To Reproduce**
Find a mac that isn't set up for development and run those install commands. The `homebrew` command won't work on windows either. It's probably not a good one to lead with.

**Expected behavior**
wick would install *somehow*

**Actual behavior**
Wick doesn't install.

**Environment:**
 - OS: macOS Venture Version 13.5.2 (22G91)
 - Architecture: 1.2 GHz Quad-Core Intel Core i7
 - Build Version: ??

**Additional context**

**Comment by jsoverson** [comment]
Thanks @rnealson, I'm looking into it now.

**Comment by rnealson** [comment]
I just submitted a PR for it https://github.com/candlecorp/wick/pull/443
