### ISSUE TITLE
Docs aren't building

### ISSUE THREAD

**Issue by jsoverson** [candlecorp/wick#466]
**Describe the bug**
The docs aren't building because rustdoc fails. There seems to be a [regression in rustc nightly](https://github.com/rust-lang/rust/issues/117598) that is causing sqlx-core to fail. Wick has to use nightly for rustdoc because we're using `--enable-index-page` 🙄

**To Reproduce**
run `rustup update` and `just rustdoc`

**Additional context**
This looks like it'll be fixed upstream. I'll keep an eye on it.

**Comment by HTGAzureX1212** [comment]
It is now fixed.

**Comment by jsoverson** [comment]
Thanks @HTGAzureX1212
