### ISSUE TITLE
Azure Blob Storage Provider

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#97]
**Is your feature request related to a problem? Please describe.**

No.  New feature request.

**Propose a solution**

I would like to connect to Azure Blob Storage to read, write and manipulate files.

**Describe alternatives you've considered**

Using the HTTP API for Azure.

**Additional context**

None

**Comment by pkedy** [comment]
@fawadasaurus Have you looked at Dapr's state store for this?

**Comment by jsoverson** [comment]
For the scope of fetching blobs, we have the azureblob component here: https://registry.candle.dev/common/azureblob.

Closing this issue since that was made without any changes to wick proper. If `wick` needs to be modified for additional functionality we can open up a new issue.
